### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by EliWillyam2020** [shadeops/houdini-pbrt-v4#1]
Hello, I hope you are having an amazing day. when I I put houdini-pbrt-v4-master folder not zip in /houdini-18.0 folder. It does not show in Houdini. I searched in /out for Pbrt node and didn't appear! I have full version in houdini. I havent touched Env variable. If you can help this would be super super amazing. Thanks for you amazing work man!

**Comment by EliWillyam2020** [comment]
and if I load it manually which I should do it every time I open houdini. when I hit render. Houdini console says CreateProcess failed for 'pbrt'

**Comment by EliWillyam2020** [comment]
I tried it in Houdini 18 and 18.5

**Comment by shadeops** [comment]
Hi @EliWillyam2020 , sorry about the long long delay. I got pulled into another project hadn't checked this one in a while.

Couple of different things.

* Verify you aren't using Houdini Apprentice. Unfortunately 3rd party renderers aren't supported by Houdini apprentice.
* The installation help was terrible so I've now cleaned this up a bit and tried to provide examples. You can find the updated help here: https://github.com/shadeops/houdini-pbrt-v4/wiki/Installation
* CreateProcess failed, might be due to `pbrt` not being found on the $PATH. You have a couple of different options.
* * Ensure the pbrt executable can be found on the $PATH.
* * Change the parameter `soho_pipecmd` on the PBRT ROP (on the Driver tab) from `pbrt` to a full path like `/opt/pbrt-v4/bin/pbrt`

**Comment by shadeops** [comment]
I've also converted the hda to an expanded type with commit 7b250a8
This avoids needing to make an hda (or renaming the existing directory).

**Comment by EliWillyam2020** [comment]
That is amazing. Thank you. Will try now
