### ISSUE TITLE
Use Packages

### ISSUE THREAD

**Issue by renderdude** [shadeops/houdini-pbrt-v4#9]
As an FYI, the exporter seems to work fine if you use packages (https://www.sidefx.com/docs/houdini/ref/plugins.html) without having to make the directory to merge soho parameters.

If you have a test hip file, I can test it further.

**Comment by shadeops** [comment]
## On Packages
This is a good point, I'll add a new option to the Wiki about setting up a Houdini Package along with an example.

The only time the [SOHOparameter merging approach](https://github.com/shadeops/houdini-pbrt-v4/wiki/Installation#method-2-advanced-install-required-for-multiple-3rd-party-renderers) is needed is if you have multiple 3rd party renderers. If you are only using houdini-pbrt-v4, then a houdini-pbrt-v4.json or houdini.env approach should be sufficient due to the SOHOparameters already including the $HFS ones.

https://github.com/shadeops/houdini-pbrt-v4/blob/master/soho/parameters/SOHOparameters#L4-L6

However if you have another renderer like RenderManForHoudini installed and it comes first in your HOUDINI_PATH, then the Pixar SOHOparameters will win and the houdini-pbrt-v4 SOHOparameters won't get loaded even if defined by a package.

## Releases
Once the pbrt-v4 book is released (at least in web form) I'll put out a proper release zip / tarball, example files and maybe a Vimeo video. The reason for not doing so currently is the interfaces and parameters are still changing some what frequently.

That said if you are looking for specific examples on how to do something just let me know.

**Comment by renderdude** [comment]
As an FYI, I've been going around and around with SideFX on this issue, and the final answer I got was no, it won't work without using your method. Here's there last response:

---
Unfortunately, Houdini looks for the first SOHOparameters file found in the HOUDINI_PATH and loads only that file. So, I don't think there's a way to get this to work without that extra file.

It might be an RFE to have a variable to make Houdini load all the instances of the file, but it's quite possible doing that might introduce other issues, since, in theory, we might end up including files multiple times (which didn't happen in the past).
---
